brew install --cask aldente
brew install --cask alt-tab
brew install --cask another-redis-desktop-manager
brew install --cask font-fantasque-sans-mono
brew install --cask font-source-code-pro
brew install --cask fsnotes
brew install --cask hyper
brew install --cask maccy
brew install --cask meld
brew install --cask vnote
brew install --cask bitwarden
brew install --cask visual-studio-code
