return {
	-- {
	--   "zbirenbaum/copilot.lua",
	--   opts = {
	--     filetypes = { ["*"] = true },
	--   },
	--   suggestion = {
	--     keymap = {
	--       accept = "<C-y>",
	--     },
	--   },
	-- },
	-- {
	-- 	"github/copilot.vim",
	-- 	init = function()
	-- 		vim.g.copilot_no_tab_map = true
	-- 	end,
	-- 	config = function()
	-- 		vim.keymap.set("i", "<C-l>", [[copilot#Accept("\<CR>")]], {
	-- 			silent = true,
	-- 			expr = true,
	-- 			script = true,
	-- 			replace_keycodes = false,
	-- 		})
	-- 	end,
	-- },
}
