[font]
# normal = { family = "JetBrainsMono Nerd Font" }
# normal = { family = "iA Writer Mono V" }
# normal = { family = "BlexMono Nerd Font" }
normal = { family = "iMWritingMono Nerd Font Propo" }
size = 12.0
[selection]
save_to_clipboard = true
